# Generated by Django 4.0.5 on 2022-06-23 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='exposure_end_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 5, 53, 23, 511912, tzinfo=utc), verbose_name='노출 종료 일자'),
        ),
        migrations.AddField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 5, 53, 23, 511912, tzinfo=utc), verbose_name='노출 시작 일자'),
        ),
    ]
