# Generated by Django 4.0.5 on 2022-06-23 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_exposure_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='exposure_end_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 10, 8, 21, 538935, tzinfo=utc), verbose_name='노출 종료 일자'),
        ),
        migrations.AlterField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 10, 8, 21, 538935, tzinfo=utc), verbose_name='노출 시작 일자'),
        ),
    ]
