# Generated by Django 4.0.5 on 2022-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_exposure_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='exposure_end_date',
            field=models.DateField(verbose_name='노출 시작 일자'),
        ),
        migrations.AlterField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateField(verbose_name='노출 시작 일자'),
        ),
    ]
